### ISSUE TITLE
"Inverse of" property can't be set

### ISSUE THREAD

**Issue by arkadib** [structureddynamics/OSF-Web-Services#10]
Hi, 

I can't save/set/import any "inverse of" object properties, neither from within OSF Ontology, nor by importing a protégé file. Is it just me?
I used 3.0; I was curious and checked 3.2 ass well with a fresh installation - no change.
Thanks,

Arkadi

**Comment by fgiasson** [comment]
Hi Arkadi,

Thanks, will look into this shortly

Thanks,

Fred

**Comment by fgiasson** [comment]
Starting to look into this.

Is the inverse property you are trying to define an Object property, Data property or annotation property?

**Comment by arkadib** [comment]
it's an Object property

**Comment by fgiasson** [comment]
Issue resolved with: b3af30059053ec3bfb28e9a795dd662e396fa9cc
