### ISSUE TITLE
getallheaders()

### ISSUE THREAD

**Issue by lpalgarvio** [structureddynamics/OSF-Web-Services#11]
Hello

getallheaders() is a function specific to mod_php, which is not the preferred method for installing and connecting to PHP on a web server. Today we use FastCGI + PHP-FPM, for both apache and nginx.

Please replace with a custom implementation or library
in OSF-Web-Services/StructuredDynamics/osf/ws/framework/WebService.php

**Comment by lpalgarvio** [comment]
example (being tested)

<?php
if (!function_exists('getallheaders'))
{
    function getallheaders()
    {
           $headers = '';
       foreach ($_SERVER as $name => $value)
       {
           if (substr($name, 0, 5) == 'HTTP_')
           {
               $headers[str_replace(' ', '-', ucwords(strtolower(str_replace('_', ' ', substr($name, 5)))))] = $value;
           }
       }
       return $headers;
    }
}

**Comment by fgiasson** [comment]
Hi @lpalgarvio,

I agree that this could be an issue with non-mod_php setups. However I am not sure this will be working. Could you dump the content of `$_SERVER` when a request is made to OSF using your FastCGI + PHP-FPM setup?

I fear that the `AUTHENTICATION` token won't be returned. If it is the cause, then we would have to do something to get the `AUTHENTICATION` token at that level. One solution incurs a rewrite rule to add it back to the headers.

If AUTHORIZATION doesn't appear, then nothing will be authenticated by OSF and every request will fail.

**Comment by fgiasson** [comment]
Resoved with https://github.com/structureddynamics/OSF-Web-Services/pull/12
