### ISSUE TITLE
Empty list ontology on Drupal site

### ISSUE THREAD

**Issue by alexukua** [structureddynamics/OSF-Web-Services#9]
Hi

After put files ontology to /data/ontologies/files
/data/ontologies/files# ls
aggr.owl  iron[1].owl  owl[1].rdf

If click Reload All  (http://drupal.local/conStruct/ontology/)
I get notice,
    owl[1].rdf reloaded
    iron[1].owl reloaded
    aggr.owl reloaded

But is below 
error :: 

that is similar to an ontology is not loaded.

Do you have any idea how to solved this problem.

**Comment by alexukua** [comment]
May be Problem with encoding returner XML files 

POST request 

http://localhost/ws/ontology/read

function=getLoadedOntologies
parameters=mode=descriptions

Ошибка синтаксического анализа XML: элемент не найден Адрес: moz-nullprincipal:{e8a04635-75ac-4700-abfe-a885033281cc} Строка 1, символ 1:

^

**Comment by fgiasson** [comment]
Theorically not. Seems the ontologies got reloaded, but the Ajax query can't still get them. If you use a JS debugger like FireBug, can you see an error from structWSF when this query is made?
